"""CLI commands for git hook management."""
from __future__ import annotations

import logging
from pathlib import Path

import typer

from .generator import generate_post_commit_hook
from .resolver import resolve_python_path

log = logging.getLogger(__name__)


def find_git_dir() -> Path | None:
    """Find .git directory in current or parent directories."""
    current = Path.cwd()

    # Check current and parents
    for path in [current] + list(current.parents):
        git_dir = path / ".git"
        if git_dir.is_dir():
            return git_dir

    return None


def hook_install_cmd(context: str | None = None) -> None:
    """Install post-commit hook in current git repository."""
    # Find git directory
    git_dir = find_git_dir()
    if not git_dir:
        typer.secho("Error: Not a git repository", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    repo_root = git_dir.parent

    # Infer context name if not provided
    if not context:
        context = repo_root.name.lower().replace(" ", "-")
        typer.echo(f"Using context name: {context}")

    # Resolve Python path
    typer.echo("Resolving Python path...")
    python_path = resolve_python_path(repo_root)

    if not python_path:
        typer.secho(
            "Error: Could not find Python with chinvex installed",
            fg=typer.colors.RED
        )
        typer.echo("Tried: .venv, py -3, python in PATH")
        typer.echo("Set CHINVEX_PYTHON to specify explicitly")
        raise typer.Exit(code=1)

    typer.echo(f"Using Python: {python_path}")

    # Generate hook
    generate_post_commit_hook(repo_root, git_dir, python_path, context)

    typer.secho(
        f"[OK] Post-commit hook installed for context '{context}'",
        fg=typer.colors.GREEN
    )
    typer.echo(f"Hook location: {git_dir / 'hooks' / 'post-commit'}")
    typer.echo(f"PowerShell script: {repo_root / '.chinvex' / 'post-commit.ps1'}")


def hook_uninstall_cmd() -> None:
    """Uninstall post-commit hook from current git repository."""
    git_dir = find_git_dir()
    if not git_dir:
        typer.secho("Error: Not a git repository", fg=typer.colors.RED)
        raise typer.Exit(code=1)

    repo_root = git_dir.parent
    hook_file = git_dir / "hooks" / "post-commit"
    ps_script = repo_root / ".chinvex" / "post-commit.ps1"

    removed = False

    if hook_file.exists():
        # Check if it's our hook
        content = hook_file.read_text()
        if "Generated by chinvex" in content:
            hook_file.unlink()
            typer.echo(f"Removed: {hook_file}")
            removed = True
        else:
            typer.secho(
                "Warning: post-commit exists but not generated by chinvex",
                fg=typer.colors.YELLOW
            )

    if ps_script.exists():
        ps_script.unlink()
        typer.echo(f"Removed: {ps_script}")
        removed = True

    if removed:
        typer.secho("[OK] Hook uninstalled", fg=typer.colors.GREEN)
    else:
        typer.echo("No chinvex hook found")


def hook_status_cmd() -> None:
    """Show git hook installation status."""
    git_dir = find_git_dir()
    if not git_dir:
        typer.secho("Not a git repository", fg=typer.colors.YELLOW)
        return

    repo_root = git_dir.parent
    hook_file = git_dir / "hooks" / "post-commit"
    ps_script = repo_root / ".chinvex" / "post-commit.ps1"

    typer.echo(f"Repository: {repo_root.name}")

    if not hook_file.exists():
        typer.secho("Post-commit hook: NOT INSTALLED", fg=typer.colors.YELLOW)
        return

    # Check if it's our hook
    content = hook_file.read_text()
    if "Generated by chinvex" not in content:
        typer.secho("Post-commit hook: EXISTS (not chinvex)", fg=typer.colors.YELLOW)
        return

    typer.secho("Post-commit hook: INSTALLED", fg=typer.colors.GREEN)

    # Extract context from PowerShell script
    if ps_script.exists():
        ps_content = ps_script.read_text()
        for line in ps_content.splitlines():
            if "# Context:" in line:
                context = line.split(":")[-1].strip()
                typer.echo(f"Context: {context}")
                break

        # Extract Python path
        for line in ps_content.splitlines():
            if "FilePath" in line and "python" in line.lower():
                typer.echo(f"Python: {line.strip()}")
                break
